name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - name: Get dependencies
        run: flutter pub get
      - name: Configure API constants
        if: ${{ env.TMDB_TOKEN != '' }}
        env:
          TMDB_TOKEN: ${{ secrets.TMDB_TOKEN }}
        run: |
          sed -i "s|static const String token = '';|static const String token = '$TMDB_TOKEN';|" lib/core/utils/constants.dart
      - name: Run tests
        run: flutter test

  build_and_release_android:
    name: Build & Release Android
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - name: Get dependencies
        run: flutter pub get
      - name: Build and sign APK
        env:
          KEYSTORE_PATH: /tmp/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "${{ secrets.MOBMOVIZZ_KEYSTORE }}" | base64 -d > $KEYSTORE_PATH
          flutter build apk --release \
            --dart-define=KEYSTORE_PATH=$KEYSTORE_PATH \
            --dart-define=KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD \
            --dart-define=KEY_ALIAS=$KEY_ALIAS \
            --dart-define=KEY_PASSWORD=$KEY_PASSWORD
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

#  build_and_release_ios:
#    name: Build & Release iOS
#    needs: build_and_test
#    runs-on: macos-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.x'
#      - name: Get dependencies
#        run: flutter pub get
#      - name: Build and sign IPA
#        uses: apple-actions/import-codesign-certs@v1
#        with:
#          p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
#          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
#      - run: flutter build ios --release
#      - name: Upload IPA
#        uses: actions/upload-artifact@v2
#        with:
#          name: release-ipa
#          path: build/ios/iphoneos/Runner.app
